<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kunker_model extends CI_Model
{

    public $table = 'kunker';
    public $id = 'id_kunker';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kunker', $q);
	$this->db->or_like('id_jenis_kunjungan', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('perihal_surat', $q);
	$this->db->or_like('lampiran_surat', $q);
	$this->db->or_like('tingkat_keamanan', $q);
	$this->db->or_like('id_fraksi', $q);
	$this->db->or_like('id_anggota_fraksi', $q);
	$this->db->or_like('id_kunker_ta', $q);
	$this->db->or_like('nama_daerah_tujuan', $q);
	$this->db->or_like('file_surat', $q);
	$this->db->or_like('file_nodin', $q);
	$this->db->or_like('pemberi_disposisi', $q);
	$this->db->or_like('isi_disposisi', $q);
	$this->db->or_like('tujuan_disposisi', $q);
	$this->db->or_like('status_disposisi', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('disposisi_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('disposisi_by', $q);
	$this->db->or_like('diposisi_note', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kunker', $q);
	$this->db->or_like('id_jenis_kunjungan', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('perihal_surat', $q);
	$this->db->or_like('lampiran_surat', $q);
	$this->db->or_like('tingkat_keamanan', $q);
	$this->db->or_like('id_fraksi', $q);
	$this->db->or_like('id_anggota_fraksi', $q);
	$this->db->or_like('id_kunker_ta', $q);
	$this->db->or_like('nama_daerah_tujuan', $q);
	$this->db->or_like('file_surat', $q);
	$this->db->or_like('file_nodin', $q);
	$this->db->or_like('pemberi_disposisi', $q);
	$this->db->or_like('isi_disposisi', $q);
	$this->db->or_like('tujuan_disposisi', $q);
	$this->db->or_like('status_disposisi', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('disposisi_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('disposisi_by', $q);
	$this->db->or_like('diposisi_note', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kunker_model.php */
/* Location: ./application/models/Kunker_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-06-09 13:59:40 */
/* http://harviacode.com */